name: Prerelease pipeline

on:
  release:
    types:
      - prereleased
    tags:
      - 'v*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GO_VERSION: '1.9.7'
  GPG_MAIL: 'infrastructure-eng@newrelic.com'
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  GPG_PRIVATE_KEY_BASE64: ${{ secrets.GPG_PRIVATE_KEY_BASE64 }} # base64 encoded
  INTEGRATION: "docker"
  ORIGINAL_REPO_NAME: 'newrelic/nri-docker'
  REPO_FULL_NAME: ${{ github.event.repository.full_name }}
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  TAG: ${{ github.event.release.tag_name }}

jobs:

  validate:
    name: Validate code via linters
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Validate code
        run: make ci/validate

  snyk:
    name: Run security checks via snyk
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Scan code for vulnerabilities
        run: make ci/snyk-test

  test-nix:
    name: Run unit tests on *Nix
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: make ci/test

  # can't run this step inside of container because of tests specific
  test-integration-nix:
    name: Run integration tests on *Nix
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: src/github.com/${{env.ORIGINAL_REPO_NAME}}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: src/github.com/${{env.ORIGINAL_REPO_NAME}}
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Integration test
        env:
          GOPATH: ${{ github.workspace }}
        run: make integration-test

  prerelease:
    name: Build binary for *Nix, create archives for *Nix, create packages for *Nix, upload all artifacts into GH Release assets
    runs-on: ubuntu-20.04
    needs: [validate, test-nix, snyk, test-integration-nix]
    steps:
      - uses: actions/checkout@v2
      - name: Pre release
        run: make ci/prerelease
      - name: Notify failure via Slack
        if: ${{ failure() }}
        uses: archive/github-actions-slack@master
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_TOKEN }}
          slack-channel: ${{ env.SLACK_CHANNEL }}
          slack-text: ":shit: Repo: ${{ env.REPO_FULL_NAME }}, prerelease for nix FAILURE!"
